name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: compile testes
      run: gcc test_calculadora.c -o test_calculadora

    - name: execute testes
      run: ./test_calculadora

    - name: compile programa principal
      run: gcc calculadora.c -o calculadora

    - name: execute programa principal
      run: ./calculadora 1 3 4
